name: Update arXiv Papers

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every midnight UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install feedparser

      - name: Run arXiv update script
        run: python fetch_arxiv.py

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          branch: main   # Change this if you're using a different branch (e.g., gh-pages)
          folder: .      # This deploys the repository root
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
